-- 코드를 입력하세요
SELECT
    FIRH.FLAVOR
    
FROM
    FIRST_HALF AS FIRH
    JOIN ICECREAM_INFO AS INFO
        ON FIRH.FLAVOR = INFO.FLAVOR

WHERE
    TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
;

