-- 코드를 입력하세요
SELECT
    BRD.TITLE
    , BRD.BOARD_ID
    , RLY.REPLY_ID
    , RLY.WRITER_ID
    , RLY.CONTENTS
    , DATE_FORMAT(RLY.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE

FROM
    USED_GOODS_BOARD AS BRD
    JOIN USED_GOODS_REPLY AS RLY
        ON BRD.BOARD_ID = RLY.BOARD_ID
        
WHERE 
    DATE_FORMAT(BRD.CREATED_DATE,'%Y-%m') = '2022-10'
    
ORDER BY
    RLY.CREATED_DATE ASC,
    BRD.TITLE ASC;
    

